user:
  name: "人不如狗"                                                       
  email: 3138731516@qq.com
  avatar: /img/avator.jpg

top_bars:
  - title: menu.home
    url: /
  - title: menu.archives
    url: /archives/